name: Flutter Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3

      - name: Install dependencies
        run: flutter pub get

      - name: Set secret content
        run: echo "$SECRET_DART_CONTENT" > lib/secret.dart
        env:
          SECRET_DART_CONTENT: ${{ secrets.SECRET_DART_CONTENT }}

      - name: Build APK
        run: flutter build apk --release

      - name: Create a Release and Upload APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/app/outputs/flutter-apk/app-release.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v1.0.0
          name: "Flutter App Release v1.0.0"
          body: "This release contains the latest version of the Flutter app."
          draft: false
          prerelease: false
